version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSL_MODE=${DB_SSL_MODE:-require}
      - JWT_SECRET=${JWT_SECRET}
      - GO_ENV=${GO_ENV:-production}
    volumes:
      - .:/app
    command: ["./main"]
